### ISSUE TITLE
Can't parse function named $

### ISSUE THREAD

**Issue by e0da** [koalaman/shellcheck#245] opened 2014-10-28 18:12 UTC
I know it's silly, but I have a function called $ to facilitate copying and pasting command line snippets which are prefixed with $.

``` sh
function $ {
  "$@"
}
```

So the $ triggers SC1000, and I just disable that. But no matter what I try with ignoring, quoting, whatever, shellcheck doesn't wan't to parse past this function.

```
In functions.zsh line 8:
}
^-- SC1070: Parsing stopped here because of parsing errors.
```

**Comment by koalaman** [comment] 2022-07-20 18:11
Closing this as a duplicate of Zsh support in #809

**Closed by koalaman** 2022-07-20 18:11 UTC
