### ISSUE TITLE
Using a backslash for unaliasing i not recognized

### ISSUE THREAD

**Issue by helau** [koalaman/shellcheck#552] opened 2015-12-01 15:22 UTC
The command:

\cp -vf source target

gives:
      ^––SC1001 This \c will be a regular 'c' in this context.

but here the backslash is just for using the native cp instead of an "aliased" cp.

**Comment by deryni** [comment] 2015-12-01 15:34
Duplicate of #485.

**Comment by koalaman** [comment] 2015-12-05 21:29
This is normally not necessary in scripts, but it would be better expressed as "command cp .." as described on the wiki: https://github.com/koalaman/shellcheck/wiki/SC1001

It should probably have its own special case checking though

**Closed by koalaman** 2015-12-05 21:29 UTC
Labels: duplicate
