### ISSUE TITLE
Error: Prelude.(!!): index too large

### ISSUE THREAD

**Issue by canavaroski90** [koalaman/shellcheck#762] opened 2016-10-27 11:32 UTC
linter-shellcheck enabled, linter installed and atom ide used for the test.
Ubuntu 14.04.03

Create a bash script (test.sh) with the following content;
```
# !/bin/bash

echo test1@"$tmpVar"
```
Remove the last double-quote ("). Atom throws following error:

Error: Prelude.(!!): index too large
    at parameters.exit (/home/user/.atom/packages/linter-shellcheck/node_modules/atom-linter/lib/helpers.js:47:27)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

Also mentioned in AtomLinter section.
https://github.com/AtomLinter/linter-shellcheck/issues/59

**Comment by koalaman** [comment] 2016-12-11 19:57
Is this in ShellCheck version 0.3.3? This version is over two years old. It may have been fixed by 6b84b35e for 0.3.5. 

I'm unable to reproduce it on the latest version (0.4.5) using `-f gcc` or anything else. Can you try upgrading?

**Comment by koalaman** [comment] 2016-12-18 00:35
Please reopen if you're able to reproduce this on a recent version.

**Closed by koalaman** 2016-12-18 00:35 UTC
