### ISSUE TITLE
Add URL link to know where have the full details of error

### ISSUE THREAD

**Issue by dcpc007** [koalaman/shellcheck#1065] opened 2017-11-30 16:30 UTC
Hi,
New user of shellcheck, i use the latest in tar.xz binary.

After try it, i would have the detials of some error shown, but had to search google to find where the doc was.
Maybe an URL in the shellcheck -h could be usefull ?

#### Here's a snippet or screenshot that shows the problem:
shellcheck -h

#### Here's what shellcheck currently says:
Command line options 

#### Here's what I wanted or expected to see:
Where to find details about the error ; base URLmaybe like : 
https://github.com/koalaman/shellcheck/wiki/

**Comment by Nightfirecat** [comment] 2017-11-30 18:35
Duplicate of #920

**Comment by koalaman** [comment] 2017-11-30 18:45
Totally agree. Discoverability of the wiki is definitely on the agenda. Stay tuned on the other bug.

**Closed by koalaman** 2017-11-30 18:45 UTC
