### ISSUE TITLE
Attempting to install on Windows with ghc 8.4.1 or 8.4.2 fails

### ISSUE THREAD

**Issue by Spitfire1900** [koalaman/shellcheck#1231] opened 2018-05-22 20:34 UTC
#### For bugs
- My shellcheck version: 0.4.7
- My ghc version: 8.4.2

#### Here's a snippet or screenshot that shows the problem:

```C:\cabal>ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.2

C:\cabal>cabal install ShellCheck
Resolving dependencies...
Downloading random-1.1...
Downloading regex-base-0.93.2...
Downloading syb-0.7...
Downloading primitive-0.6.3.0...
Configuring regex-base-0.93.2...
Configuring random-1.1...
Configuring primitive-0.6.3.0...
Configuring syb-0.7...
Building regex-base-0.93.2...
Building random-1.1...
Building primitive-0.6.3.0...
Building syb-0.7...
Installed regex-base-0.93.2
Downloading regex-tdfa-1.2.3...
Configuring regex-tdfa-1.2.3...
Installed random-1.1
Installed syb-0.7
Downloading json-0.9.2...
Building regex-tdfa-1.2.3...
Configuring json-0.9.2...
Installed primitive-0.6.3.0
Downloading tf-random-0.5...
Configuring tf-random-0.5...
Building json-0.9.2...
Building tf-random-0.5...
Installed json-0.9.2
Installed tf-random-0.5
Downloading QuickCheck-2.11.3...
Configuring QuickCheck-2.11.3...
Building QuickCheck-2.11.3...
Installed QuickCheck-2.11.3
Installed regex-tdfa-1.2.3
Downloading ShellCheck-0.4.7...
Configuring ShellCheck-0.4.7...
Building ShellCheck-0.4.7...
Failed to install ShellCheck-0.4.7
Build log ( C:\Users\e018503\AppData\Roaming\cabal\logs\ghc-8.4.2\ShellCheck-0.4
.7-EIx8zZ6lVnL5Lyrrd0XqR6.log ):
Preprocessing executable 'shellcheck' for ShellCheck-0.4.7..
Building executable 'shellcheck' for ShellCheck-0.4.7..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file'
s other-modules: Paths_ShellCheck

                 ShellCheck.AST

                 ShellCheck.ASTLib

                 ShellCheck.Analytics

                 ShellCheck.Analyzer

                 ShellCheck.AnalyzerLib

                 ShellCheck.Checker

                 ShellCheck.Checks.Commands

                 ShellCheck.Checks.ShellSupport

                 ShellCheck.Data

                 ShellCheck.Formatter.CheckStyle

                 ShellCheck.Formatter.Format

                 ShellCheck.Formatter.GCC

                 ShellCheck.Formatter.JSON

                 ShellCheck.Formatter.TTY

                 ShellCheck.Interface

                 ShellCheck.Parser

                 ShellCheck.Regex
[ 1 of 19] Compiling Paths_ShellCheck ( dist\build\shellcheck\autogen\Paths_Shel
lCheck.hs, dist\build\shellcheck\shellcheck-tmp\Paths_ShellCheck.o )
[ 2 of 19] Compiling ShellCheck.Regex ( ShellCheck\Regex.hs, dist\build\shellche
ck\shellcheck-tmp\ShellCheck\Regex.o )

ShellCheck\Regex.hs:33:17: warning: [-Wsimplifiable-class-constraints]
    * The constraint `RegexMaker Regex CompOption ExecOption String'
        matches an instance declaration
      instance RegexMaker Regex CompOption ExecOption String
        -- Defined in `Text.Regex.TDFA.String'
      This makes type inference for inner bindings fragile;
        either use MonoLocalBinds, or simplify it using the instance
    * In the type signature:
        make :: RegexMaker Regex CompOption ExecOption String =>
                String -> Regex
      In the expression:
        let
          make ::
            RegexMaker Regex CompOption ExecOption String => String -> Regex
          make = makeRegex
        in make str
      In an equation for `mkRegex':
          mkRegex str
            = let
                make ::
                  RegexMaker Regex CompOption ExecOption String => String -> Reg
ex
                make = makeRegex
              in make str
   |
33 |     let make :: RegexMaker Regex CompOption ExecOption String => String ->
Regex
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^
[ 3 of 19] Compiling ShellCheck.AST   ( ShellCheck\AST.hs, dist\build\shellcheck
\shellcheck-tmp\ShellCheck\AST.o )
[ 4 of 19] Compiling ShellCheck.Interface ( ShellCheck\Interface.hs, dist\build\
shellcheck\shellcheck-tmp\ShellCheck\Interface.o )
[ 5 of 19] Compiling ShellCheck.Data  ( ShellCheck\Data.hs, dist\build\shellchec
k\shellcheck-tmp\ShellCheck\Data.o )
[ 6 of 19] Compiling ShellCheck.Formatter.Format ( ShellCheck\Formatter\Format.h
s, dist\build\shellcheck\shellcheck-tmp\ShellCheck\Formatter\Format.o )
[ 7 of 19] Compiling ShellCheck.Formatter.TTY ( ShellCheck\Formatter\TTY.hs, dis
t\build\shellcheck\shellcheck-tmp\ShellCheck\Formatter\TTY.o )
[ 8 of 19] Compiling ShellCheck.Formatter.JSON ( ShellCheck\Formatter\JSON.hs, d
ist\build\shellcheck\shellcheck-tmp\ShellCheck\Formatter\JSON.o )
[ 9 of 19] Compiling ShellCheck.Formatter.GCC ( ShellCheck\Formatter\GCC.hs, dis
t\build\shellcheck\shellcheck-tmp\ShellCheck\Formatter\GCC.o )
[10 of 19] Compiling ShellCheck.Formatter.CheckStyle ( ShellCheck\Formatter\Chec
kStyle.hs, dist\build\shellcheck\shellcheck-tmp\ShellCheck\Formatter\CheckStyle.
o )
[11 of 19] Compiling ShellCheck.ASTLib ( ShellCheck\ASTLib.hs, dist\build\shellc
heck\shellcheck-tmp\ShellCheck\ASTLib.o )
[12 of 19] Compiling ShellCheck.Parser ( ShellCheck\Parser.hs, dist\build\shellc
heck\shellcheck-tmp\ShellCheck\Parser.o )
[13 of 19] Compiling ShellCheck.AnalyzerLib ( ShellCheck\AnalyzerLib.hs, dist\bu
ild\shellcheck\shellcheck-tmp\ShellCheck\AnalyzerLib.o )

ShellCheck\AnalyzerLib.hs:60:10: error:
    * No instance for (Semigroup Checker)
        arising from the superclasses of an instance declaration
    * In the instance declaration for `Monoid Checker'
   |
60 | instance Monoid Checker where
   |          ^^^^^^^^^^^^^^
cabal: Leaving directory 'C:\Users\e018503\AppData\Local\Temp\cabal-tmp-12280\Sh
ellCheck-0.4.7'
cabal: Error: some packages failed to install:
ShellCheck-0.4.7-EIx8zZ6lVnL5Lyrrd0XqR6 failed during the building phase. The
exception was:
ExitFailure 1
```

#### Here's what I wanted or expected to see (8.2.1 succedes):
```
C:\cabal>ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1

C:\cabal>cabal install ShellCheck
Resolving dependencies...
Downloading mtl-2.2.2...
Configuring random-1.1...
Configuring primitive-0.6.3.0...
Configuring mtl-2.2.2...
Configuring syb-0.7...
Building mtl-2.2.2...
Building primitive-0.6.3.0...
Building syb-0.7...
Building random-1.1...
Installed random-1.1
Downloading text-1.2.3.0...
Configuring text-1.2.3.0...
Installed syb-0.7
Building text-1.2.3.0...
Installed primitive-0.6.3.0
Configuring tf-random-0.5...
Installed mtl-2.2.2
Configuring regex-base-0.93.2...
Building tf-random-0.5...
Building regex-base-0.93.2...
Installed regex-base-0.93.2
Installed tf-random-0.5
Configuring QuickCheck-2.11.3...
Building QuickCheck-2.11.3...
Installed QuickCheck-2.11.3
Installed text-1.2.3.0
Downloading parsec-3.1.13.0...
Configuring parsec-3.1.13.0...
Building parsec-3.1.13.0...
Installed parsec-3.1.13.0
Configuring regex-tdfa-1.2.3...
Configuring json-0.9.2...
Building regex-tdfa-1.2.3...
Building json-0.9.2...
Installed json-0.9.2
Installed regex-tdfa-1.2.3
Configuring ShellCheck-0.4.7...
Building ShellCheck-0.4.7...
Installed ShellCheck-0.4.7
```

**Comment by koalaman** [comment] 2018-05-23 02:38
Presumably a duplicate of #1224

**Closed by koalaman** 2018-05-23 02:38 UTC
Labels: duplicate
