### ISSUE TITLE
Shellcheck 0.4.4 ignores shebang regarding POSIX errors (SC2039)

### ISSUE THREAD

**Issue by zhimsel** [koalaman/shellcheck#733] opened 2016-09-08 22:34 UTC
Happens in both `vim` and `nvim`, using neomake.

Shellcheck will return SC2039 errors, claiming that I've made the script POSIX compliant, regardless of the shebang or any options. Event hardcoding `bash` will result in an SC2039 error for the following script: 

```shell
#!/bin/bash

if [[ $1 == 'hi' ]]
then
  echo hi
fi
```

The errors are not present while running `shellcheck` from the command line (which I'm still trying to figure out why; it returns no output even if there are errors in neomake).

**Comment by koalaman** [comment] 2016-09-12 06:14
Looks like this is a neomake bug: https://github.com/neomake/neomake/issues/602

Please reopen if the issue is not fixed by their https://github.com/blueyed/neomake/commit/8226a2860eaa5353ff77e924225dbd7b8c750093

**Closed by koalaman** 2016-09-12 06:14 UTC

**Comment by zhimsel** [comment] 2016-09-12 19:32
Ok, thanks! Didn't see that.
