### ISSUE TITLE
SC2068 false positive

### ISSUE THREAD

**Issue by nickstoughton** [koalaman/shellcheck#345] opened 2015-04-09 16:08 UTC
Usage such as

my_func ${@+"$@"}

trigger "SC2068 Double quote array expansions, otherwise they're like $* and break on spaces." However, the usage explicitly quotes $@ if it is set, and never breaks on spaces.

**Comment by koalaman** [comment] 2015-04-09 20:02
Very true. This is a duplicate of #288

**Closed by koalaman** 2015-04-09 20:02 UTC
Labels: duplicate
