### ISSUE TITLE
New POSIX UB: lastpipe

### ISSUE THREAD

**Issue by Arthur2e5** [koalaman/shellcheck#523] opened 2015-10-26 22:40 UTC
Common form of the error:

```sh
blah | while read ... # or any other thing that changes the current shell env
```

This breaks things in a silent way, and is almost definite (the only exception being experiment/test scripts).

**Comment by koalaman** [comment] 2015-10-28 04:18
Do you mean that shellcheck should warn that this might overwrite the environment?

**Comment by Arthur2e5** [comment] 2015-10-28 04:52
The problem quite the opposite. Users often expect it to change the environment instead.

**Comment by deryni** [comment] 2015-10-28 14:13
Indeed. That's why the SO question ([Modifying variable inside while loop is not remembered](http://stackoverflow.com/questions/16854280/modifying-variable-inside-while-loop-is-not-remembered)) is listed in the SO bash tag wiki.

**Comment by koalaman** [comment] 2015-10-28 15:30
Isn't this covered by SC2030 and SC2031 already?

**Comment by Arthur2e5** [comment] 2015-10-28 20:55
No. `echo a | read -r b; echo $b` gives All good.

**Comment by Arthur2e5** [comment] 2015-10-28 20:59
This also exposes a problem that shellcheck thinks `b` needs to be used.

**Comment by koalaman** [comment] 2015-10-28 22:45
When I paste `echo a | read -r b; echo $b` on shellcheck.net, I get this:

      echo a | read -r b; echo $b
                       ^––SC2030 Modification of b is local (to subshell caused by pipeline).
                               ^––SC2031 b was modified in a subshell. That change might be lost.
                               ^––SC2086 Double quote to prevent globbing and word splitting.

**Comment by Arthur2e5** [comment] 2015-10-29 01:12
Uh-oh. I looked at `echo a | read -r b`, got a unused and simply thought…

**Comment by koalaman** [comment] 2015-10-31 21:53
No problem, assuming current support is sufficient and closing

**Closed by koalaman** 2015-10-31 21:53 UTC
