### ISSUE TITLE
Duplicate messages in Neovim

### ISSUE THREAD

**Issue by ebiscaia** [koalaman/shellcheck#2684] opened 2023-02-05 11:16 UTC
#### For bugs
- My shellcheck version (`shellcheck --version` or "online"): 0.9.0 (installed using Mason)
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)

Hi guys, not sure if it is a problem with shellcheck, neovim or when they both work together. Here are some screenshots to those who are interested.

![05-05-23](https://user-images.githubusercontent.com/74695273/216815626-a69144b5-c162-43cf-ada1-1a506c396eb0.png)
![05-07-23](https://user-images.githubusercontent.com/74695273/216815637-03bf13a9-95cd-4fde-8b3a-daf65d27a0ea.png)

Thanks,

Eddie

**Comment by brother** [comment] 2023-02-06 07:35
You should get two messages there, one for the decimal as shown but also a style note about the unnecessary dollar sign in the parentheses.
I am not sure what went wrong but something is broken indeed.

**Comment by WhaleJ84** [comment] 2023-03-28 16:07
![image](https://user-images.githubusercontent.com/43613409/228301341-3179d498-7242-4d3f-95c3-377611500501.png)
 I get the same issue, even on lines where there's definitely not more than 1 error.

**Comment by sanchay9** [comment] 2023-09-30 12:37
getting same issue with neovim, any workaround for this?

**Comment by jackyhevey** [comment] 2023-10-09 13:59
Have you used bash-lsp sametime?    https://github.com/bash-lsp/bash-language-server

As bash-lsp will use `shellcheck`  default

My solution:

not install `shellcheck` in mason(null-ll neovim)
install it system `global`
bash-lsp will use the global `shellcheck`

**Comment by sanchay9** [comment] 2023-10-10 09:55
Thank you! That fixes it.
I did not know that bash-lsp already has shellcheck enabled.
Although you can keep it via mason only (system install not required), it just needs to be in the path.

**Comment by brother** [comment] 2023-10-10 10:41
I think we can close this now.
It's not a bug in shellcheck and we have a suggested solution that people can find if they try to solve something similar. Thanks a bunch everyone for participating!

**Closed by brother** 2023-10-10 10:41 UTC
