### ISSUE TITLE
Shellcheck crashes when expanding an array element inside arithmetic expansion inside a heredoc

### ISSUE THREAD

**Issue by Deotronic** [koalaman/shellcheck#2846] opened 2023-10-17 22:13 UTC
#### For bugs
- Rule Id (if any, e.g. SC1000): None; Shellcheck crashes with an error
- My shellcheck version (`shellcheck --version` or "online"): 0.9.0 and "online"
- [ X ] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ X ] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
#! /usr/bin/env bash
my_array=("20" "30")
cat <<EOF >> ./test
$(( 1 + my_array[1] ))
EOF
```

#### Here's what shellcheck currently says:
version 0.9.0:
```
deotronic$ shellcheck ./array-test.bash
shellcheck: Unimplemented: OuterToken (Id 31) (Inner_T_UnparsedIndex "./array-test.bash" (line 4, column 18) "1")
CallStack (from HasCallStack):
  error, called at src/ShellCheck/CFG.hs:890:14 in ShllChck-0.9.0-74ac27dc:ShellCheck.CFG
```

online:
```
[Line 1:](javascript:setPosition(1, 1))
#! /usr/bin/env bash
^-- Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally.
```

If you modify the script to wrap the array in ${...}, then both versions only give the style warning:
```
In array-test.bash line 4:
$(( 1 + ${my_array[1]} ))
        ^------------^ SC2004 (style): $/${} is unnecessary on arithmetic variables.
```

Similarly, if you take the whole thing out of the heredoc (but don't use ${...}), then it executes correctly and Shellcheck does not crash and does not issue the style warning.

In all cases, when executed, the script generates the expected output.

#### Here's what I wanted or expected to see:
Shellcheck should not crash on that line.

It isn't clear to me if you're *supposed* to expand arrays inside heredocs without using ${...}. But Shellcheck should either advise you add them *or* should process that situation cleanly.

**Comment by drybjed** [comment] 2023-11-27 13:56
I can confirm the same issue happening on `shellcheck` v0.9.0 included in Debian. The issue can be found in [this script](https://github.com/debops/debops/blob/master/ansible/roles/pki/files/secret/pki/lib/pki-authority#L369), the error from `shellcheck` I get is:

```
shellcheck: Unimplemented: OuterToken (Id 2438) (Inner_T_UnparsedIndex "./ansible/roles/pki/files/secret/pki/lib/pki-authority" (line 369, column 66) "'pki_default_sign_base'")
CallStack (from HasCallStack):
  error, called at src/ShellCheck/CFG.hs:890:14 in ShellCheck-0.9.0-4IN8x9FCDQNHDD2Xpzltgi:ShellCheck.CFG
```

Looking forward for the fix.

**Comment by koalaman** [comment] 2023-12-11 03:14
Very nice catch! This happened because of the combination of two peculiarities of Bash parsing: 1. Parsing bash array indices is [known to be undecidable](https://www.oilshell.org/blog/2016/10/20.html), because the interpretation depends on whether or not the array has previously been declared associative, and 2. Here documents are not normal language syntax, but rather parsed after the linefeed following commands that reference them.

ShellCheck deals with the first issue by delaying the parsing of array indices until the whole script is parsed, and then fairly naively looking for `declare -A` statements. It deals with the second by adding any pending here documents to a queue, and parsing them after an `\n`, and then associating them with the relevant command at the end.

Unfortunately ShellCheck did it in that order, meaning that indices were reparsed before the here docs were re-associated with the commands, thereby causing array references inside here docs to remain unprocessed.

The bug must have been around forever, but it only became symptomatic in 0.9.0 because of the new support for building Control Flow Graphs, which failed to handle the unprocessed array references. This particular bug has been fixed by flipping the order, and the CFG builder should avoid failing for any such issues in the future.

Thanks!

**Closed** 2023-12-11 03:14 UTC

**Comment by Deotronic** [comment] 2023-12-11 17:12
Interesting! Thanks for the details and the fix!
