### ISSUE TITLE
Test expression parsing failure shouldn’t be fatal

### ISSUE THREAD

**Issue by shdown** [koalaman/shellcheck#412] opened 2015-07-13 18:11 UTC
Script:
````bash
mode=-f
file=foo
[ "$mode" "$file" ] && echo bar
````
ShellCheck output:
````
In foo.bash line 3:
[ "$mode" "$file" ] && echo bar
^-- SC1073: Couldn't parse this test expression.
          ^-- SC1072: Expected "]". Fix any mentioned problems and try again.
````

There shouldn’t be a “fatal” parser error, since it’s a perfecly legal bash/sh code.

**Comment by koalaman** [comment] 2015-07-18 23:08
Duplicate of #51

**Closed by koalaman** 2015-07-18 23:08 UTC
