### ISSUE TITLE
Add support for printf format string for date/times

### ISSUE THREAD

**Issue by rdiez** [koalaman/shellcheck#1294] opened 2018-07-17 16:07 UTC
Bash' printf supports a special format string for date/time formatting like this:

printf -v CURRENT_DATE "%(%F %H:%M:%S)T"

At the moment, you get the following spurious warning for that kind of placeholder:

warning: This format string has 1 variables, but is passed 0 arguments. [SC2183]

**Comment by koalaman** [comment] 2018-07-22 18:11
Duplicate of #1171

**Closed by koalaman** 2018-07-22 18:11 UTC
