### ISSUE TITLE
cannot be found by home-brew

### ISSUE THREAD

**Issue by bwanaaa** [koalaman/shellcheck#2200] opened 2021-04-10 01:44 UTC
Apple M1 Mac 
brew updated
brew upgraded

#### Here's a snippet or screenshot that shows the problem:

``` 
% brew install shellcheck
Error: shellcheck: no bottle available!
You can try to install from source with:
  brew install --build-from-source shellcheck
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

```

**Comment by silverlyra** [comment] 2021-04-12 20:35
(duplicate of #2162)

**Closed** 2021-07-27 16:44 UTC
