### ISSUE TITLE
Feature Request: shellcheckwiki from command line

### ISSUE THREAD

**Issue by xxfelixxx** [koalaman/shellcheck#1122] opened 2018-02-21 01:56 UTC
Hi, 

I'm not sure where this suggestion goes, so I'm putting it here. 
ShellCheck is awesome! but the messages are quite terse.  It would be nice to have the tool
spit out more verbose info at the comand line.

I wrote a tool to do this, called shellcheckwiki, which pulls the SCxxxx page from the wiki and prints 
it to the console.  It would be nice if this was possible just using shellcheck itself, to speed up the development process (for the user).

Here's a demo:  https://asciinema.org/a/J0z2MZTJe8iesCGk2OsEL3sWb
Link to repo: https://github.com/xxfelixxx/shellcheckwiki

Thanks,

Felix

**Comment by Nightfirecat** [comment] 2018-02-21 07:05
Duplicate of #920?

**Comment by xxfelixxx** [comment] 2018-02-21 11:56
Sort of like #920...but I think the actual content of the wiki in the CLI is more useful than a link you have to follow...

**Comment by jasonkarns** [comment] 2019-01-29 19:40
I love this idea! Would it make more sense to have the wiki pulled down as man pages using some existing md-to-roff converter?

**Comment by brother** [comment] 2024-01-22 19:29
One could clone the wiki git repo and then execute a md 2 roff-script over that. Simple enough.

As has been stated in #1365 the purpose of the wiki is to be online and stay updated and thus having a static copy is not desired.

**Closed by brother** 2024-01-22 19:29 UTC
