### ISSUE TITLE
Enhancing source-path directive

### ISSUE THREAD

**Issue by tomaszdrozdz** [koalaman/shellcheck#2658] opened 2023-01-09 09:31 UTC
I have project structure:

```
my_project\
|- .shellcheckrc
|- lib\
    |- l.sh
|-bin\
    |- A\
        |- a.sh
            --------------------
            #!/bin/bash
            . "${PROJECT_DIR}/lib/l.sh"
            some code
            --------------------
    |- b.sh
            --------------------
            #!/bin/bash
            . "${PROJECT_DIR}/lib/l.sh"
            some code
            --------------------
```

.shellcheckrc file is at the "root" of my_project.  

PROJECT_DIR variable is "auto generated" to point to my_project dir.  

I can put multiple source-path directive to .shellcheckrc:
```
source-path=SCRIPTDIR/../../
source-path=SCRIPTDIR/../
```

But it would be nice if I could in .shellcheckrc just put something like:
```
source-path=SHELLCHECKRC
```
so shellcheck interprets it as relative to .shellcheckrc file.

**Comment by sellout** [comment] 2023-01-18 00:49
Duplicate of #1959.

**Closed** 2023-01-19 15:06 UTC
